### ISSUE TITLE
Ticketmaster API integration request

### ISSUE THREAD

**Issue by Frenchcooc** [Bearer/Pizzly#109]
In october, Pizzly teams up with Hacktoberfest 2020 to increase the number of API integrations to up to 100 APIs 🎉 To learn more about how to participate and win, look at [our Hacktoberfest guide](https://github.com/Bearer/Pizzly/blob/master/HACKTOBERFEST.md).

**Ticketmaster** has been identified as a major API that we would love to support. Your mission is to create a configuration file that make this API ready to be used by Pizzly developers.

Here are a few links to help you achieve this task:

* [Ticketmaster official website](https://www.ticketmaster.com/)
* [Ticketmaster Developers Portal](https://degratnik.github.io/)
* [Ticketmaster's OAuth documentation](https://degratnik.github.io/products-and-docs/apis/oauth/)
* [Pizzly's guide on how to add a new integration](https://github.com/Bearer/Pizzly/wiki/Reference-:-Integrations#adding-a-new-integration)

If you are interested in adding this integration to Pizzly, please comment below first, to tell other contributors that you're on it. 

Once you've the configuration ready, please create a PR that links to this issue ([more detail in our Hacktoberfest guide](https://github.com/Bearer/Pizzly/blob/master/HACKTOBERFEST.md)). Here's an [example of a similar PR](https://github.com/Bearer/Pizzly/pull/143/files) that was recently accepted.

Happy hacking! 👨‍🎤

**Comment by listopadiya** [comment]
I would be glad to help with it 🙂

**Comment by listopadiya** [comment]
I've checked Ticketmaster API documentation and tried to add integration for it, but didn't succeed.

Looks like Ticketmaster currently do not use OAuth with their APIs. They propose to use apiKey with all public APIs instead of OAuth - https://degratnik.github.io/products-and-docs/apis/getting-started/. Although OAuth guide is still in place - https://degratnik.github.io/products-and-docs/apis/oauth/, but it requires client ID. I tried to create developer account and application in it, but it didn't contain client ID property, just apiKey and secret...

I tried to use apiKey as client ID (just in case) but obviously it didn't work, tried it locally with such integration:
```
{
  "name": "Ticketmaster",
  "auth": {
    "authType": "OAUTH2",
    "authorizationURL": "https://oauth.ticketmaster.com/oauth/authorize",
    "tokenURL": "https://oauth.ticketmaster.com/oauth/token",
    "tokenParams": { "grant_type": "authorization_code" },
    "authorizationParams": { "response_type": "code", "scope": "all" }
  },
  "request": {
    "baseURL": "https://app.ticketmaster.com/${headers.package}/${headers.version}/",
    "headers": {
      "Accept": "application/json",
      "Authorization": "Bearer ${auth.accessToken}",
      "User-Agent": "Pizzly"
    }
  }
}
```
and got just error in response:
```
{"error":"invalid_client","error_description":"client_id is invalid","errors":[{"status":"400","id":"invalid_client","detail":"client_id is invalid"}]}
```

Didn't find any information on it except some issues like this one https://github.com/ticketmaster-api/ticketoffice-app/issues/4. So probably apiKey is the only way to support Ticketmaster now and this issue relates to another one #74 .

**Comment by Frenchcooc** [comment]
Thanks @listopadiya for reporting this! Sharing this thread to Ticketmaster support.

**Comment by Frenchcooc** [comment]
Closing this issue unfortunately as I haven't heard back from Ticketmaster
