### ISSUE TITLE
Github GraphQL API

### ISSUE THREAD

**Issue by ogizanagi** [Bearer/Pizzly#183]
Hello there 👋🏻 

The current Github integration provides a proxy to call the Rest API v3.
I'm wondering if there is any plan to support the GraphQL API?

**Comment by markmichon** [comment]
Hey 👋,

The way integrations are set up, they don't support multiple base URLs. That said, you could duplicate the GitHub integration, name it something else, and swap out the URL. AFAIK the auth scheme for v4 hasn't changed, and since GraphQL requests are just XHR calls under the hood there should be no issues with using Pizzly's proxy features.

Happy to accept a PR for a GraphQL specific one if you get it working 👍
