### ISSUE TITLE
Error with empty "scopes" in configuration

### ISSUE THREAD

**Issue by kevinvermeersch** [Bearer/Pizzly#191]
When I try to authenticate to a service with a configuration where the "scopes" field is empty I get an error.

![Screenshot 2021-01-14 at 18 43 29](https://user-images.githubusercontent.com/2557662/104628375-6f76b380-5698-11eb-9841-0e5cf082eb67.png)

Looking through the code I found that line 59 throws an error because "config" is undefined.

https://github.com/Bearer/Pizzly/blob/6db035d15f2dd24f2a22a6e1ee42d9000b87088a/src/legacy/auth/v3/strategies/oauth2/auth-code.ts#L51-L61

**Comment by markmichon** [comment]
Hey @kevinvermeersch, make sure that the API you're using doesn't require a scope (or require that the scopes set in your account with them match those sent). Every time I've hit a similar problem it normally is due to some mismatch with the scopes entered.

From the snippet you sent, config is defined further up and comes from the integration config. I may be mistaken, but I'm pretty sure you can't get far enough in the auth process without the config being defined.

Another potential area that might bet the cause is a flawed configuration file for the API. Is this a custom integration or one that is already included with Pizzly?

**Comment by kevinvermeersch** [comment]
@markmichon Thanks for the reply. I'm making a custom integration for Mautic (mautic.org). It's oauth configuration does not need any scope and fails if a scope is set.

I think there's typo on line 59. It should be: **scope: scopes || config?.scope || [],**

Optional chaining uses "?." instead of "!."

**Comment by markmichon** [comment]
Changing the non-nullish chain to an optional chain doesn't appear to break APIs with scopes, but I'm unable to test if it fixes your problem as all the APIs I have access to are scoped. Could you try the change locally and see if it fixes your issue?

**Comment by kevinvermeersch** [comment]
I'm not a TypeScript expert but I can confirm that this fixed my problem.

**Comment by Fastmind-inc** [comment]
@markmichon API's such as Mailchimp are not scoped which then end up causing that issue.

**Comment by markmichon** [comment]
This should now be resolved. Regarding @Fastmind-inc's comment, I can confirm auth with mailchimp works with the fix as well (though api calls to mailchimp still require some extra work due to the way they require the client to send the server address)
